### ISSUE TITLE
[support]

### ISSUE THREAD

**Issue by Git-Reternos** [bigenergy/windowlogging-renewed#1]
![螢幕擷取畫面 2024-12-14 004256](https://github.com/user-attachments/assets/f7ab910b-2ef0-44bb-b7cd-b0d1a8ee8178)
vanilla glass and copper

**Comment by Git-Reternos** [comment]
Do i still need to install other mod to work like description's image?

**Comment by Mysticpasta1** [comment]
having the same issue

**Comment by bigenergy** [comment]
![Screenshot_4](https://github.com/user-attachments/assets/2dc75a8e-2bb5-48d6-9f96-897403fc4be6)

working

**Comment by bigenergy** [comment]
> having the same issue

check without other mods, maybe something changes the render

**Comment by Mysticpasta1** [comment]
it is definitely other mods causing it but unsure which one

**Comment by bigenergy** [comment]
To find the problem you need a specific mod that breaks the render, if you manage to find it, open a new issue
